---
title: "Codebook"
author: "Timothy Dutton"
toc: true
date-modified: last-modified
date-format: "D MMM, YYYY"
number-sections: true
number-depth: 2
callout-appearance: minimal
crossref:
  chapters: true
format: 
  html:
    theme: united
editor: visual
---

> The codebook should be applied in accordance with Coding Rules (see @sec-rules).

# Information-Seeking Prompts

Interviewer prompts that are not information-seeking, including minimal encouragers (see @nte-me) and clarification-/confirmation-seeking prompts (see @nte-clarification), will not be coded unless otherwise specified.

## "Open" Questions {#sec-oq}

::: panel-sidebar

A

:   Anchor: initial prompt to introduce the topic of concern for the interview

    -   "Tell me what (you have come/we are) here to talk about."

    -   Not always open-ended

INV

:   Open-ended initial invitation

BQ

:   Open-ended breadth question

DQ

:   Open-ended depth question

AE

:   Anything else: yes/no questions that use the phrase "anything else"
:::

Open-ended questions encourage an elaborate response but do not tell an interviewee what specific information is required. Interviewees have the freedom to choose what information will be reported and to narrate what happened in their own words (see @nte-oq).

1.  **Open-ended initial invitation:** These questions encourage interviewees to report everything about an event or occurrence of the event. They are typically the first prompt to start talking about the event (or an event occurrence).
    -   *Tell me everything that happened at Dan’s house, from the very beginning to the end.*

    -   *What happens when Jim hurts you?*
2.  **Open-ended breadth questions**: These encourage interviewees to report another act/activity/detail, without specifying what information is required.
    -   *Then what happened?*

    -   *What else happened the night Amy got sick?*
3.  **Open-ended depth questions**: These questions request further elaboration about a pre-disclosed event/experience/detail, without specifying precisely what information is required.
    -   They can target a current topic (e.g., “Tell me more about X,”)

        -   *What happened when you started to set the food out?*

        -   *Tell me everything you remember about swimming in the lake.*

    -   They can re-introduce a previously mentioned one (e.g., “Earlier you said X. Tell me more about X”).
4.  **Open-ended descriptive questions:** These invite elaborate detail about an object/person/location (rather than an action). These are useful for getting descriptive/contextual information, but not ideal for finding out what happened
    -   *Tell me about the car.*

    -   *Tell me more about the woman.*

## Topic Shifts

Code the first prompt in a series of consecutive prompts with the same topic.

C

:   Context: prompts requesting background/descriptive information that is not specific to an episode of abuse or about the generic abuse script (see @nte-context)

    -   **Suspect**: facts about the suspect (name, age, occupation, height, skin colour)

    -   **People**: facts about any other relevant people

    -   **Location**: facts about locations (e.g., layout of house, child's address at the time)

    -   **Time**: temporally relevant facts (e.g., what classroom/term the child was in at the time)

    -   **Contact**: how the child and suspect came to know each other, how often child and suspect meet

    -   **Body**: sexual body part knowledge

    ([BUT]{.underline} note that these details can be episodic if the interviewer is attempting to particularise a specific occurrence; e.g., “what year were you in the time it happened in the back garden?”). 

RFI

:   'Request for information': prompts requesting specific episodic remembered details surrounding abusive acts

    -   **Suspect**: physical description (not usually relevant for known suspects like family members, teachers)

    -   **People**: questions about the presence of any other people

    -   **Location:** to establish where the abuse happened or confirm presence in a place

    -   **Clothes**

    -   **Words**: gist of conversations

    -   **Object**

    -   **Timeframe**: prompts used to establish/narrow down the timeframe of abuse (time of day/month/year)

    -   **Time**: other temporal details

    -   **Disclosure**: details about prior disclosures of the abuse (including disclosure time, circumstances, recipients, potential discussions of the event, and reactions to disclosure by both the child and recipients)

    -   **Action**: questions about actions and movements that occurred

        -   Includes questions aimed at establishing what happened (as part of a sequence of events)

            -   "What did he do?"

            -   "You'd been inside the house?"

            -   "Did you go in his car?"

            -   "You didn't pick your sister up?"

        -   Even if a prompt mentions a location/object/person, if it’s primarily about what happened (or didn't happen), and is aimed at eliciting a sequence of events, it should be coded as `action`.

            -   "Where were you going?"

        -   Apart from wh-questions like "What did you do?", these questions are most often leading questions (see @nte-lq): yes/no questions, forced-choice questions or confirmation-seeking questions that introduce new information.

    -   **Gap**: other prompts requesting new details (see @nte-clarification). These include questions about reasons, causes, or explanations.

        -   often higher-order questions (e.g., "What made him say that?", "How did you know that?") that are also implicitly about actions

ACT

:   Details that are central to, and delineate the structure of, the abusive act (e.g., nature, invasiveness).

    -   **Action**: seeking details explaining the overall actions that happened during the abuse (e.g., "What did he do?")
    -   **Gap**: questions about reasons, causes, or explanations.
    -   **Location**: where people are positioned in relation to the environment where the abuse happened
    -   **Body**: movement and positioning of victim/suspect body parts
    -   **Clothes**: placement and removal (establishing whether skin-to-skin contact occurred)
    -   **Subjective**: victim’s thoughts and emotions
    -   **Sensations**: victim’s physical sensations (pain)
    -   **Perspective**: what the victim could see or hear
    -   **Face**: suspect’s facial expression
    -   **Object**: movement and position of objects used by suspect
    -   **Injury**: injuries resulting from the abusive act
    -   **Words**: gist of conversations during abuse
    -   **Tone**: tone of suspect’s words
    -   **Duration**: duration of abusive act

## Event Shifts

E

:   This code is used to signal the start of the phase of the interview discussing a particular occurrence of abuse or the generic script of the abuse.

    -   Event number (**1,2,3...**): corresponds to the order in which the event is raised during the interview (not related to the labels used, e.g., first time)

    -   **Generic**: prompts from the interviewer seeking to elicit information about generalities/commonalities across occurrences (e.g., what usually happens)

        -   Also use this code when multiple offences have been established, and the interviewer's prompts are in past tense, but the prompts are not explicitly about a specific time.

    -   **Unknown**: If the interviewer and child have not explicitly established that there are multiple offences, and the interviewer seems to be prompting about a specific time, even if the child provides some generic responses.

    -   **Ambiguous**: use when it is unclear if the interviewer aims to elicit specific/episodic or generic details. This applies when the interviewer's prompts are generic (e.g., in timeless present tense) when the interviewer and child have not explicitly established that there are multiple offences.

    This code applies to the first information-seeking prompt or clarification-seeking prompt about the particular occurrence/generic script that the child responds to with forensically relevant details.

## Repeated Abuse Prompts

### Prompt

Interviewer prompts to determine whether \>1 event occurred:

1.  Asking whether a previously mentioned abusive act occurred on one or more occasions.

2.  Establishing whether certain abusive acts occurred on the same or different occasions.

3.  Asking how many times the abuse occurred.

4.  Asking whether an occurrence of abuse ever occurred before the described occasion.

5.  Asking whether an occurrence of abuse ever occurred since the described occasion.

6.  Asking whether the described occasion was the only time it occurred.

7.  Clarifying the child’s previous response suggesting repeated abuse (only applies when 1.-6. do not apply).

### Time {#sec-time}

Interviewer prompts to focus on eliciting episodic detail about a particular occurrence:

1.  Using the term “first time.”

2.  Using the term “last time.”

3.  Using a label previously provided by the child.

4.  Using the terms “another time,” “other time,” “different time” (includes "any other time")

5.  Using the term “remember best.”

6.  Using the term “one time,” “a time,” “any time.”

7.  Using the term “that time” in reference to the label raised by the child.

8.  Using the term “next time.”

9.  Using terms that suggest episodic details “did it ever happen on a birthday”

::: {.callout-tip title="When to use `time` codes"}
This code applies only to the interviewer's initial attempts to elicit details about a specific occurrence of abuse that has not yet been discussed. Once further questioning about that particular occurrence begins, the code no longer applies. It becomes relevant again only when the interviewer tried to initiate discussion about a new, previously unexplored occurrence.
:::

### Difference

Interviewer prompts about differences among/between events:

1.  Any differences across events?

2.  Specific detail same or different across events?

3.  During which event did a specific detail occur?

### Similarity

Interviewer prompts about similarities among/between events:

1.  Were the events similar?

2.  Same location?

### Temporal

Interviewer prompts requesting information about when each event occurred, frequency of abuse, and the temporal relationships among events (e.g., order, gap between events). This code is only relevant for when repeated abuse has been established in the interview. For example, asking how many times the abuse occurred would be coded as `temporal` and not `prompt>3` if the child has already disclosed multiple occurrences of abuse in the interview.

# Child Responses

+---------------+-----------------+---------------+---------------+---------------+
| [-@sec-d]     | [-@sec-cue]     | [-@sec-story] | [-@sec-ot]    | [-@sec-react] |
|               |                 |               |               |               |
| d             | cue             | story         | ot            | react         |
+---------------+-----------------+---------------+---------------+---------------+
| -   re1       | -   tense       | -   1         | -   silence   | -   accept    |
|               |                 |               |               |               |
| -   re2       | -   optional    | -   2         | -   filler    | -   reject    |
|               |                 |               |               |               |
| -   cue       | -   conditional | -   3         | -   refusal   | -   same      |
|               |                 |               |               |               |
| -   single    | -   you         |               | -   idk       | -   risk      |
|               |                 |               |               |               |
| -   ambiguous |                 |               | -   sidetrack | -   safe      |
|               |                 |               |               |               |
|               |                 |               | -   question  |               |
|               |                 |               |               |               |
|               |                 |               | -   repeat    |               |
|               |                 |               |               |               |
|               |                 |               | -   multiple  |               |
|               |                 |               |               |               |
|               |                 |               | -   cue       |               |
+---------------+-----------------+---------------+---------------+---------------+

## D {#sec-d}

Initial disclosure: the earliest point at which the child disclosed an abusive event, irrespective of whether they elaborated upon what happened ("to talk about the rude stuff", "he touched me down there")

-   **re1**: Disclosure of abuse including episodic labels/details that are differentiated as different occurrences of abuse.

-   **re2:** Disclosure that abuse has occurred a certain number of times or “more than once” without specific episodic labels/details.

-   **cue:** Disclosure of abuse including linguistic cues (see below) suggesting that there is more than one event.

    -   Include the cue type (e.g., `ot>cue>tense`; see @sec-cue)

-   **single:** Disclosure of a single episode of abuse

-   **ambiguous:** Disclosure of abusive experience that could be a single episode or repeated

## Cue {#sec-cue}

Linguistic cues from the child’s response suggesting they are recalling general script information. *This code is used prior to the interviewer establishing repeated abuse (i.e., prior to any `event>generic`/`event>number` shifts).*

-   **Optional:** indicate that an act may or may not occur in a given instance.

    -   Markers: *sometimes*, *usually*, *maybe*, *might, or*
    -   Example: “We usually have the first snack on the roof.”
    -   Example: “Then we go on the bus or our mommy picks us up.”

-   **Conditional:** require specific conditions for an act to occur

    -   Markers: *if*, *when*, *because*, *whenever*
    -   Example: “Whenever we go to Grandma’s, we have cookies.”

-   **Tense:** describes general routines or procedures using timeless present tense

    -   Example: “We order food at a restaurant.”

-   **Habitual:** Describe repeated actions in the past

    -   Markers: *used to*, *would* (habitual use)
    -   Example: “He used to order food at a restaurant.”

-   **Always:** Emphasise consistent repetition across all instances.

    -   Markers: *always*, *every time*, *each time*
    -   Example: “We always eat popcorn during movies.”

-   **Multiple**: A response that contains details from other episodes of abuse besides the particular episode that the interviewer is asking about.

## Story {#sec-story}

Narrative details (see @nte-detail) provided in response to **open questions** (see @sec-oq).

-   **1:** What happened in the lead-up to the abuse? (Establishes suspect’s intent/knowledge to commit the act(s)).

-   **2:** What happened during the abusive act(s)? (Illegal acts of high investigative relevance).

-   **3:** What happened after the abuse until no other offending occurred? (Includes what made it stop and what happened after).

## OT {#sec-ot}

Off-track responses are responses that do not provide the information requested by the interviewer's prompt or do not address the issue raised by the interviewer. These are usually unproductive responses that do not confirm, deny, or provide new forensically relevant information (except for *multiple* & *cue*).

-   **Silence**: The child's response is comprised of only filler words (e.g., umm, ahh) or the child does not provide a verbal or gestural response to the question.

    -   *Silent turns and filler-only turns are not coded as off-track responses if the interviewer treats them as incomplete by immediately repeating or clarifying the question (see point 7 in @sec-rules)*

-   **Refusal**: The child explicitly declines to answer the interviewer’s question, such as by stating, 'I don’t want to talk about that' or 'I won’t answer that.'"

-   **IDK**: Responses that express lack of memory, knowledge, or understanding, such as 'I don’t know,' 'I don’t remember,' 'I’m not sure,' or 'I don’t get what you mean.' This does not include when the child also elaborates on their response, providing a guess about what the answer might be (e.g., When did that happen?” Child: “I don't know, but I think it was before Christmas some time, probably around the fall”).

    -   Minimal responses like “no,” “not really,” or “I don’t think so” should not be coded as off-track if they directly address the interviewer’s question by denying the information raised. The exception is 'no' responses to yes/no questions that probe for memory or knowledge (e.g., 'Do you remember what he was wearing?')

-   **Sidetrack**: A response that is overtly off-topic and non-substantive, such as shifting to an unrelated topic, discussing irrelevant events, or providing irrelevant personal anecdotes.

-   **Question**: An uninvited question posed by the child in response to the interviewer’s prompt. This includes questions that divert attention from the topic at hand, such as 'Why do you need to know that?' or 'Can I go now?' Clarification-seeking questions, rhetorical questions, or questions recounted in dialogue (e.g., 'Then he said, "What are you doing here?"') are excluded because they engage with the topic or provide relevant context.

-   **Repeat**: A response that repeats information already discussed in the interview without elaborating or adding new details.

-   **Cue**: A response that contains linguistic cues that the child is recalling generic script information when the interviewer is asking about a particular episode of abuse. [This only applies when the interviewer and child have explicitly established that there was repeated abuse.]{.underline}

    -   Include the cue type (e.g., `ot>cue>tense`; see @sec-cue)

### React {#sec-react}

[**SPECIAL (not child response) Interviewer reactions to off-track responses will be coded.**]{.underline} The code (adapted from [Earhart et al. 2019](https://onlinelibrary.wiley.com/doi/10.1002/bsl.2141)) should be applied to the interviewer's subsequent prompt.

**Accept**: The interviewer accepts the child’s off-track response by either:

-   Making a supportive or encouraging comment (e.g., “That’s okay,” “Thank you for telling me that”),

-   Moving on to a different topic or the next logical question, without returning to the original prompt,

-   Refocusing the conversation on something the child has previously mentioned, without signalling dissatisfaction.

**Reject**: The interviewer does not accept the off-track response, and instead continues to ask about the same information or makes negative comments about the child's response, increasing the pressure to provide an answer.

1.  Increases pressure on the child to respond: The interviewer repeats/reframes the question or continues to ask about the same information, ignoring the child's off-track response.

    -   Interviewer: "Has it happened many times?"

    -   Child: "I don’t know."

    -   Interviewer: "How many times has it happened?"

    -   The interviewer's subsequent prompt signals to the child that they have not answered the question and that their response was not legitimate.

2.  Comments that signal dissatisfaction with the child’s off-track response

::: {.callout-tip title="Usage Tip"}
**If the interviewer responds to an off-track response with a clarification-seeking prompt (e.g., “You don’t know?”, “Not really?”), do not treat this as the reaction prompt.**\

Wait to code the next information-seeking prompt, which represents the interviewer’s actual strategic response to the off-track content.
:::

Additionally, code the interviewer's subsequent prompt in relation to the original eliciting question as:

-   **same**: same question type category

-   **risk**: riskier question type category (higher number)

-   **safe**: safer question type category (lower number)

If more than one category applies, use the higher numbered category.

+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| Type              | Explanation                                                                                                                                                                                                                                                                                                       | Example                                                                   |
+===================+===================================================================================================================================================================================================================================================================================================================+===========================================================================+
| 1\. Invitation    | Free recall questions which encouraged the child to freely recall any aspect of the event(s) and minimal encouragers that included very little information but prompted the child to continue.                                                                                                                    | ‘Tell me everything that happened’ ‘Uhuh’ Echoing the child's words       |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| 2\. Directive     | Free recall questions on a cued topic, including wh- questions (e.g. what, where, when, who, why).                                                                                                                                                                                                                | 'Where did that happen?'                                                  |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| 3\. Option-posing | All questions that required a ‘Yes’ or ‘No’ answer (including "can you" questions) and forced choice questions which include answers for the child to choose between.                                                                                                                                             | 'Did you hit your head or your knee?’                                     |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| 4\. Multiple      | Single utterances in which the interviewer asked more than one question, and utterances in which the interviewer summarised what the child had said previously, either with or without including a direct question (children often respond to these summaries as if they have been asked to confirm the summary). | ‘Did you see the man? What did he look like? Where was he?'               |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| 5\. Suggestive    | Questions that introduce information the child has not mentioned previously or that imply a desired response. The question may also include other suggestive techniques, such as mentioning what the interviewer has heard from other sources.                                                                    | Your mum told me your brother hurt you, what do you remember about that?’ |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| 6\. Unknown       | Questions that were not clearly transcribed, parts of the question were missing, or questions which were unfinished, either due to the child interrupting or the interviewer changing their question.                                                                                                             | ‘When <unclear> the man?’                                                 |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+

: Question Type Categories (adapted from Griffiths Question Map) {.info .hover .sm}

# Other Codes

These codes should be applied to the first relevant line in the interview.

**Closure**

-   When the interviewer either asks “are there any other times X…” (or similar) and the child says no and no further occurrences arise, or when the interviewer begins procedural duties at the end of the interview (e.g., was everything you told me today the truth?).

**Break**

-   Suspension in transcript (break in the recording)

**Indistinct**

Response/prompt is inaudible/indistinct (as noted in the transcription) and cannot be inferred based on context

-   Includes issues like fault in recording or inaudible segments.

**Interruption**

-   A situation that causes a deviation from the substantive phase of the interview while the recording continues.

-   Includes situations where the interviewer proposes a break, then continues with the interview anyway.

# Coding Rules {#sec-rules}

1.  Codes should be applied under 3 columns. Column 1: Open Questions & Topic Shifts; Column 2: Event Shifts and Repeated Abuse Prompts; Column 3: Child Responses & Other Codes.

2.  Codes are not mutually exclusive, more than one code can be applied at each turn (use commas to separate them when applicable).

3.  If multiple sub-categories of the same code apply to a single turn, use the syntax: `code>sub-category1:sub-category2:...` (e.g., `cue>conditional:optional`, `story>1:2`). The order of the sub-categories should match the order in which they appear in the turn.

4.  Child responses to interviewer facilitators (non-suggestive words, such as 'ok' or 'yes') and minimal encouragers (see @nte-me) that encourage them to continue an ongoing response to the previous prompt are attributed to the preceding information-seeking prompt.

5.  Code the final prompt from the interviewer if more than one question is asked in a turn.

6.  If it takes the interviewer multiple turns to finish asking their question, code the final turn. This can happen when the interviewer is contextualising their prompt by summarising or clarifying previously discussed information.

7.  If the interviewer repeats a prompt when the child does not respond (i.e., filler word or silence), or in order to clarify, only code the final prompt.

> | *Q. All right. So I just want to work out before we go into the other bits, when you say, “my thingy”, what do you mean by “my thingy”?*
> | *A.  Um - -*
> | *Q.  What’s another word that you have for your thingy?*

8.  Coding ends when the interviewer either asks “are there any other times X…” (or similar) and the child says no and no further occurrences arise, or when the interviewer begins procedural duties at the end of the interview (e.g., was everything you told me today the truth?). If the interviewer returns to questioning about the abuse, continue coding.

# Notes

::: {#nte-context .callout-note title="Context"}
Context prompts are usually used for requesting semantic information ("known information rather than remembered). Note that it may depend on context; if a child has only been to a house where the abuse took place *one time,* then a question about where the kitchen was in relation to the bedroom is *episodic.* This also applies when talking about a house the child used to live in. But, if the interviewer and child are talking about the child’s current home, this is not a memory, and so it is context.

**A quick rule** (keeping in mind that quick rules are not always perfect): Ask yourself two questions: 1) Is the prompt about act(s) of abuse \[including particularising detail about when and where\]?  If NO (but still relevant to the abuse), it’s probably contextual.
:::

::: {#nte-clarification .callout-note title="Clarification-/Confirmation-Seeking Prompts"}
*Clarification-seeking* prompts do **not seek new information** but instead clarify details already shared by the child (i.e., clarifying inconsistencies and vagueness in the child's account)

-   When you say your brother, which brother is that?

-   You heard him say that?

Confirmation-seeking yes/no questions are used by many interviewers in the sample to summarise what the child has said and allow the child to check the interviewer's recall for accuracy. These questions do not move the interview forward, as they reflect back on information previously provided by the child without seeking additional forensically relevant information.

-   These questions are often used (a) near the end of the interview, (b) right before transitioning to a different topic, and (c) to bring up information previously provided by the child in order to formulate the next question in a logical manner.

In contrast, information-seeking prompts aim to gather new details that expand the narrative.

-   You said that dad drinks. Had dad been drinking that night?

-   How did you know he drank that night?
:::

::: {#nte-me .callout-note title="Minimal Encouragers"}
Minimal encouragers signal to a speaker that they are being listened to and understood without breaking the interviewee’s train of thought. Minimal encouragers can be verbal (e.g., saying ‘uh huh’, ‘Mhmm’, repeating a few words the interviewee said) or non- verbal (e.g., head nodding).

-   ***Child**: He gave me his number. **Interviewer**: Uh-huh.*

<!-- -->

-   ***Child**: We went in the shed. **Interviewer**: In the shed? **Child**: Yeah, and I sat on the couch and then he got the pictures.*
:::

::: {#nte-oq .callout-note title="Helpful Tips"}
1.  **Requesting precision doesn’t make a question specific.** Asking someone to be precise (e.g., “Tell me exactly what happened”) doesn’t make a question specific. Consideration must be given to whether the question dictates what information is being requested.

<!-- -->

2.  **Requesting someone to be elaborate doesn’t make a question open-ended.** Asking someone to be elaborate (e.g., “Tell me everything you can remember about the colour of his tie”) doesn’t make a question open. Consideration must be given to whether the question dictates what information is being requested.

<!-- -->

3.  **The words ‘Tell’, ‘Explain’, and ‘Describe’ do not make questions open-ended.** When deciding if a question is open-ended or specific, don’t focus on key words, but rather, whether the question is telling the interviewee what precise details the interviewer is looking for. (E.g., “Tell me what you won your gold medal for?”)

<!-- -->

4.  **Focus on the structure of the question, not the response it elicits.** Sometimes interviewers try to soften an open-ended question with the phrases, ‘Can you ...’, ‘Are you able to tell me ...’, and ‘Do you know/remember ...’ to make it sound more polite. Although they may intend to invite an elaborate response (and many interviewees will interpret them that way), they allow for a ‘yes’ or ‘no’ response.
:::

::: {#nte-lq .callout-note title="Leading Questions"}
Leading questions presume or raise an aspect or detail that hasn’t already been mentioned by the child or established to be true.

-   May or may not pressure the child to agree ("... right?")

-   Often suggest that a particular response is expected (e.g., “Joe hit you, didn’t he?”)

Others presume one or more details and ask the interviewee to talk about them without checking first whether they happened (e.g., “Tell me about Susan’s dog” when it hasn’t been established that Susan had a dog). A simple yes/no or forced-choice questions is leading if it raises a highly specific detail, an issue of contention or narrows response options, irrespective of whether the interviewee is given the option to reject suggested details.

**Quick rule**: If the question contains words, terminology, events or details that haven’t been mentioned by the child, the question can be classified as leading.
:::

::: {#nte-detail .callout-note title="Narrative Details"}
Child responses can be broken down into propositions (see prior studies of narrative development; e.g., [Fivush et al., 1995](https://www.sciencedirect.com/science/article/pii/S0022096585710302), [Principe et al., 2013](https://www.sciencedirect.com/science/article/pii/S0885201413000300)). A proposition is a subject + verb construction. Sometimes a proposition can have more than one subject ("Dad and I had dinner") or more than one verb ("I left and went to the bathroom"). A narrative detail will be defined as a proposition that answers the open-ended question and that does not repeat information from the question or the **immediately** previous child response.
:::
